### ISSUE TITLE
Provide a simple skipper setup example

### ISSUE THREAD

**Issue by qvistgaard** [donovanmuller/spring-cloud-skipper-platform-openshift#1]
I would really like to see a setup example pom for setting up a skipper server jar with the openshift platform. I would love to take it for a spin

**Comment by donovanmuller** [comment]
This repo was in context of [this blog post](https://blog.switchbit.io/spring-cloud-skipper-as-a-service-broker/). Perhaps the post will give you a better idea/example.

It's probably also worth following the progress on https://github.com/spring-cloud/spring-cloud-skipper/issues/552
